### ISSUE TITLE
Hardcoded server IP address

### ISSUE THREAD

**Issue by stratosgear** [t0mer/gotenberg-ui#2]
Hey,

It seems that you have forgotten the hardcoded IP address of the gotenberg server, in case a user tries to upload a file, instead of rendering an online url.

Check your templates/index.html :)

**Comment by nodecentral** [comment]
Hi, just wanted to add to this, as i think its the same thing @stratosgear raised

When i upload a file, it takes ages, fails, and then takes me this address and port

`192.168.0.252:3010/forms/libreoffice/convert`

Which i assume is hardcoded..

**Comment by nodecentral** [comment]
Oh yes, i can see the ip:port listed in here..

https://github.com/t0mer/gotenberg-ui/blob/65e602f3a25ea07f89fc5ed4414a9a9ad9478b25/gotenbergui/templates/index.html

**Comment by stratosgear** [comment]
I guess no one is around.  The MR is not even merged... :(

**Comment by t0mer** [comment]
Hi,
I'm sorry for not getting back to you sooner.
I was busy with other projects.
I merged your PR, and I will publish a new container version.

Cheers 🙂
